baseURL = "https://johntorres.me/"
copyright = "© 2025 John Torres. Licensed under CC BY 4.0."
defaultContentLanguage = "en"
enableRobotsTXT = true
title = "John Torres"

[module]
    [[module.imports]]
        path = "github.com/clente/hugo-bearcub"

[markup]
    [markup.highlight]
        lineNos = true
        lineNumbersInTable = false
        noClasses = false

[params]
    dateFormat = "2006-01-02"
    description = "Personal website of John Torres"
    generateSocialCard = true
    themeStyle = "original"
    title = "John Torres"
    madeWith = "Powered by [Hugo](https://gohugo.io/) and [Bear Cub](https://github.com/clente/hugo-bearcub)."

    [params.author]
        name = "John Torres"
        email = "john@johntorres.me"

[menus]
    [[menus.main]]
        name = "Home"
        identifier = "home"
        pageRef = "/"
        weight = 10

    [[menus.main]]
        name = "Blog"
        identifier = "blog"
        pageRef = "/blog"
        weight = 20

    [[menus.main]]
        name = "GitHub"
        identifier = "github"
        url = "https://github.com/johnjtorres"
        weight = 30

    [[menus.main]]
        name = "LinkedIn"
        identifier = "linkedin"
        url = "https://linkedin.com/in/johnjamestorres"
        weight = 30
