baseURL = "https://johntorres.me/"
copyright = "© 2025 [John Torres](/) • [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)"
defaultContentLanguage = "en"
enableRobotsTXT = true
title = "John Torres"

[module]
    [[module.imports]]
        path = "github.com/clente/hugo-bearcub"

[markup]
    [markup.highlight]
        lineNos = true
        lineNumbersInTable = false
        noClasses = false

[params]
    dateFormat = "2006-01-02"
    description = "Homepage of John Torres"
    generateSocialCard = true
    themeStyle = "original"
    title = "John Torres"
    madeWith = "Built with [Hugo](https://gohugo.io/) + [Bear Cub](https://github.com/clente/hugo-bearcub)"

    [params.author]
        name = "John Torres"
        email = "john@johntorres.me"

[menus]
    [[menus.main]]
        name = "Home"
        identifier = "home"
        pageRef = "/"
        weight = 10

    [[menus.main]]
        name = "Blog"
        identifier = "blog"
        pageRef = "/blog"
        weight = 20
